fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "backend_info",
            "setup_installation_info",
            "apply_windows_integration",
            "finish_setup_handoff",
            "restart_application",
            "main_window_ready",
            "app_update_status",
            "check_app_update",
            "repair_application",
            "cancel_app_update",
            "install_app_update_now",
            "desktop_appearance",
            "browser_integration_status",
            "repair_browser_integration",
            "remove_browser_integration",
            "take_browser_action",
            "prompt_torrent_default_app",
            "open_native_path",
            "reveal_native_path",
            "notify_native",
            "open_compact_window",
            "focus_main_window",
        ]),
    ))
    .expect("failed to build the Ravyn Tauri application manifest");
}
