//! The declarative operation table that must stay in exact parity
//! with the Axum router.

use super::OperationSpec;

pub(super) const OPERATIONS: &[OperationSpec] = &[
    op!("get", "/health", "health", "System", "Basic liveness check"),
    op!(
        "get",
        "/health/live",
        "liveness",
        "System",
        "Process liveness check"
    ),
    op!(
        "get",
        "/health/ready",
        "readiness",
        "System",
        "Backend readiness check"
    ),
    op!(
        "get",
        "/metrics",
        "metrics",
        "System",
        "OpenMetrics endpoint"
    ),
    op!(
        "get",
        "/openapi.json",
        "openapiDocument",
        "System",
        "OpenAPI document"
    ),
    op!(
        "get",
        "/v1/jobs",
        "listJobs",
        "Jobs",
        "List jobs",
        "200",
        true,
        false,
        Some("JobPage")
    ),
    op!(
        "get",
        "/v1/jobs/summary",
        "getJobSummary",
        "Jobs",
        "Get aggregate queue statistics and recent jobs",
        "200",
        false,
        false,
        Some("JobSummary")
    ),
    op!(
        "post",
        "/v1/jobs",
        "createJob",
        "Jobs",
        "Create a job",
        "201",
        false,
        true,
        Some("Job")
    ),
    op!(
        "post",
        "/v1/jobs/metalink",
        "createMetalinkJob",
        "Jobs",
        "Create an HTTP job from a bounded Metalink v4 document",
        "201",
        false,
        true,
        Some("Job")
    ),
    op!(
        "post",
        "/v1/jobs/batch",
        "createJobBatch",
        "Jobs",
        "Create multiple jobs",
        "207",
        false,
        true,
        None
    ),
    op!(
        "post",
        "/v1/jobs/actions",
        "applyBulkJobAction",
        "Jobs",
        "Apply an action to multiple jobs",
        "200",
        false,
        true,
        None
    ),
    op!(
        "post",
        "/v1/jobs/import-text",
        "importTextJobs",
        "Jobs",
        "Import jobs from text",
        "207",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/jobs/{id}",
        "getJob",
        "Jobs",
        "Get a job",
        "200",
        false,
        false,
        Some("Job")
    ),
    op!(
        "patch",
        "/v1/jobs/{id}",
        "updateJob",
        "Jobs",
        "Update a job",
        "200",
        false,
        true,
        Some("Job")
    ),
    op!(
        "delete",
        "/v1/jobs/{id}",
        "deleteJob",
        "Jobs",
        "Delete a job",
        "204",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/jobs/{id}/outputs",
        "listJobOutputs",
        "Jobs",
        "List job output artifacts",
        "200",
        true,
        false,
        Some("JobOutputPage")
    ),
    op!(
        "get",
        "/v1/library",
        "listLibraryEntries",
        "Library",
        "Search the persistent download library",
        "200",
        true,
        false,
        Some("LibraryPage")
    ),
    op!(
        "get",
        "/v1/library/duplicates",
        "findLibraryDuplicates",
        "Library",
        "Find exact duplicate candidates in the persistent library",
        "200",
        false,
        false,
        Some("DuplicateCandidateList")
    ),
    op!(
        "get",
        "/v1/library/{id}",
        "getLibraryEntry",
        "Library",
        "Get a persistent library entry",
        "200",
        false,
        false,
        Some("LibraryEntry")
    ),
    op!(
        "delete",
        "/v1/library/{id}",
        "deleteLibraryEntry",
        "Library",
        "Move a library entry to trash or purge it",
        "200",
        false,
        false,
        Some("DeleteLibraryResult")
    ),
    op!(
        "post",
        "/v1/library/{id}/restore",
        "restoreLibraryEntry",
        "Library",
        "Restore a trashed library entry",
        "200",
        false,
        false,
        Some("LibraryEntry")
    ),
    op!(
        "post",
        "/v1/templates/preview",
        "previewFilenameTemplate",
        "Library",
        "Preview a sanitized filename template",
        "200",
        false,
        true,
        Some("TemplatePreview")
    ),
    op!(
        "post",
        "/v1/library/import",
        "startLibraryImport",
        "Library",
        "Start a bounded import of an existing directory",
        "202",
        false,
        true,
        Some("LibraryImportStatus")
    ),
    op!(
        "get",
        "/v1/library/import",
        "getLibraryImportStatus",
        "Library",
        "Get the current library import status",
        "200",
        false,
        false,
        Some("LibraryImportStatus")
    ),
    op!(
        "delete",
        "/v1/library/import",
        "cancelLibraryImport",
        "Library",
        "Request cancellation of the active library import",
        "200",
        false,
        false,
        Some("LibraryImportStatus")
    ),
    op!(
        "post",
        "/v1/library/verify",
        "verifyLibraryEntries",
        "Library",
        "Verify persisted files and mark missing entries",
        "200",
        false,
        false,
        Some("VerifyLibraryReport")
    ),
    op!(
        "post",
        "/v1/library/relocate",
        "repairLibraryRelocations",
        "Library",
        "Repair missing library paths by content identity",
        "200",
        false,
        true,
        Some("RelocationReport")
    ),
    op!(
        "post",
        "/v1/library/move/preflight",
        "preflightLibraryMove",
        "Library",
        "Validate a physical Library-root move",
        "200",
        false,
        true,
        Some("LibraryMovePreflight")
    ),
    op!(
        "get",
        "/v1/library/move",
        "getLibraryMoveStatus",
        "Library",
        "Get the latest durable Library-root move status",
        "200",
        false,
        false,
        Some("LibraryMoveStatus")
    ),
    op!(
        "post",
        "/v1/library/move",
        "startLibraryMove",
        "Library",
        "Start a transactional physical Library-root move",
        "202",
        false,
        true,
        Some("LibraryMoveStatus")
    ),
    op!(
        "delete",
        "/v1/library/move",
        "cancelLibraryMove",
        "Library",
        "Request cancellation of an uncommitted Library-root move",
        "200",
        false,
        false,
        Some("LibraryMoveStatus")
    ),
    op!(
        "get",
        "/v1/presets",
        "listDownloadPresets",
        "Presets",
        "List reusable download presets",
        "200",
        false,
        false,
        Some("DownloadPresetList")
    ),
    op!(
        "post",
        "/v1/presets",
        "createDownloadPreset",
        "Presets",
        "Create a reusable download preset",
        "201",
        false,
        true,
        Some("DownloadPreset")
    ),
    op!(
        "get",
        "/v1/presets/{id}",
        "getDownloadPreset",
        "Presets",
        "Get a download preset",
        "200",
        false,
        false,
        Some("DownloadPreset")
    ),
    op!(
        "put",
        "/v1/presets/{id}",
        "updateDownloadPreset",
        "Presets",
        "Update a download preset",
        "200",
        false,
        true,
        Some("DownloadPreset")
    ),
    op!(
        "delete",
        "/v1/presets/{id}",
        "deleteDownloadPreset",
        "Presets",
        "Delete a download preset",
        "204",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/basket",
        "listBasketItems",
        "Basket",
        "List staged download basket items",
        "200",
        false,
        false,
        Some("BasketItemList")
    ),
    op!(
        "post",
        "/v1/basket",
        "addBasketItem",
        "Basket",
        "Add a staged download to the basket",
        "201",
        false,
        true,
        Some("BasketItem")
    ),
    op!(
        "delete",
        "/v1/basket",
        "clearBasket",
        "Basket",
        "Clear every staged basket item"
    ),
    op!(
        "patch",
        "/v1/basket/{id}",
        "updateBasketItem",
        "Basket",
        "Update a staged basket item",
        "200",
        false,
        true,
        Some("BasketItem")
    ),
    op!(
        "delete",
        "/v1/basket/{id}",
        "deleteBasketItem",
        "Basket",
        "Delete a staged basket item",
        "204",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/basket/reorder",
        "reorderBasket",
        "Basket",
        "Reorder all staged basket items",
        "200",
        false,
        true,
        Some("BasketItemList")
    ),
    op!(
        "post",
        "/v1/basket/start",
        "startBasket",
        "Basket",
        "Create jobs from staged basket items",
        "200",
        false,
        false,
        Some("BasketStartResult")
    ),
    op!(
        "get",
        "/v1/profiles",
        "listUserProfiles",
        "Profiles",
        "List user profiles",
        "200",
        false,
        false,
        Some("UserProfileList")
    ),
    op!(
        "post",
        "/v1/profiles",
        "createUserProfile",
        "Profiles",
        "Create a user profile",
        "201",
        false,
        true,
        Some("UserProfile")
    ),
    op!(
        "get",
        "/v1/profiles/{id}",
        "getUserProfile",
        "Profiles",
        "Get a user profile",
        "200",
        false,
        false,
        Some("UserProfile")
    ),
    op!(
        "put",
        "/v1/profiles/{id}",
        "updateUserProfile",
        "Profiles",
        "Update a user profile",
        "200",
        false,
        true,
        Some("UserProfile")
    ),
    op!(
        "delete",
        "/v1/profiles/{id}",
        "deleteUserProfile",
        "Profiles",
        "Delete a user profile",
        "204",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/profiles/{id}/activate",
        "activateUserProfile",
        "Profiles",
        "Activate a user profile",
        "200",
        false,
        false,
        Some("ActivateProfileResponse")
    ),
    op!(
        "post",
        "/v1/trust/preview",
        "previewTrustScore",
        "Trust",
        "Evaluate an explainable advisory trust score",
        "200",
        false,
        true,
        Some("TrustReport")
    ),
    op!(
        "get",
        "/v1/jobs/{id}/trust",
        "getJobTrustScore",
        "Trust",
        "Evaluate and persist a job trust score",
        "200",
        false,
        false,
        Some("TrustReport")
    ),
    op!(
        "get",
        "/v1/system/cleanup-policies",
        "getCleanupPolicies",
        "System",
        "Get automatic cleanup retention policies",
        "200",
        false,
        false,
        Some("CleanupPolicies")
    ),
    op!(
        "put",
        "/v1/system/cleanup-policies",
        "putCleanupPolicies",
        "System",
        "Replace automatic cleanup retention policies",
        "200",
        false,
        true,
        Some("CleanupPolicies")
    ),
    op!(
        "post",
        "/v1/system/cleanup",
        "runLibraryCleanup",
        "System",
        "Run library cleanup immediately",
        "200",
        false,
        false,
        Some("CleanupReport")
    ),
    op!(
        "get",
        "/v1/statistics",
        "getPersonalStatistics",
        "Statistics",
        "Get user-facing library and bandwidth statistics",
        "200",
        false,
        false,
        Some("PersonalStatistics")
    ),
    op!(
        "get",
        "/v1/jobs/{id}/media-items",
        "listMediaItems",
        "Media",
        "List persisted media or playlist items",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "get",
        "/v1/jobs/{id}/media-items/{item_id}/outputs",
        "listMediaItemOutputs",
        "Media",
        "List output artifacts linked to one media item",
        "200",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/jobs/{id}/media-summary",
        "mediaItemSummary",
        "Media",
        "Get aggregate state for a media or playlist job",
        "200",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/jobs/{id}/media-items/{item_id}/retry",
        "retryMediaItem",
        "Media",
        "Create a retry job for one media item",
        "201",
        false,
        false,
        Some("Job")
    ),
    op!(
        "post",
        "/v1/jobs/{id}/media-items/retry-failed",
        "retryFailedMediaItems",
        "Media",
        "Retry failed media items in a bounded batch",
        "200",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/jobs/{id}/segments",
        "listJobSegments",
        "Jobs",
        "List persisted HTTP segments",
        "200",
        true,
        false,
        Some("SegmentPage")
    ),
    op!(
        "get",
        "/v1/jobs/{id}/actions",
        "listJobActions",
        "Jobs",
        "List post-processing journal entries",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "get",
        "/v1/jobs/{id}/logs",
        "listJobLogs",
        "Jobs",
        "List job logs",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/jobs/{id}/pause",
        "pauseJob",
        "Jobs",
        "Pause a job",
        "204",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/jobs/{id}/resume",
        "resumeJob",
        "Jobs",
        "Resume a job",
        "204",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/jobs/{id}/cancel",
        "cancelJob",
        "Jobs",
        "Cancel a job",
        "204",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/jobs/{id}/retry",
        "retryJob",
        "Jobs",
        "Retry a job",
        "204",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/media/probe",
        "probeMedia",
        "Media",
        "Probe media formats",
        "200",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/media/archive",
        "listMediaArchive",
        "Media",
        "List persistent downloaded media identities",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "delete",
        "/v1/media/archive",
        "deleteMediaArchiveEntry",
        "Media",
        "Delete one persistent media identity",
        "204",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/system/dependencies",
        "listDependencies",
        "System",
        "Inspect external dependencies"
    ),
    op!(
        "get",
        "/v1/system/capabilities",
        "systemCapabilities",
        "System",
        "Inspect backend capabilities"
    ),
    op!(
        "get",
        "/v1/settings",
        "getSettings",
        "Settings",
        "Get persistent settings"
    ),
    op!(
        "patch",
        "/v1/settings",
        "updateSettings",
        "Settings",
        "Update persistent settings",
        "200",
        false,
        true,
        None
    ),
    op!(
        "post",
        "/v1/settings/reset",
        "resetSettings",
        "Settings",
        "Reset persistent settings"
    ),
    op!(
        "post",
        "/v1/settings/validate",
        "validateSettings",
        "Settings",
        "Validate a settings patch and report every failing field"
    ),
    op!(
        "get",
        "/v1/system/database",
        "databaseStatus",
        "Database",
        "Inspect database integrity"
    ),
    op!(
        "post",
        "/v1/system/database/backup",
        "createDatabaseBackup",
        "Database",
        "Create an online database backup",
        "201",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/system/database/backups",
        "listDatabaseBackups",
        "Database",
        "List database backups",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/system/database/backups/{name}/verify",
        "verifyDatabaseBackup",
        "Database",
        "Verify a database backup"
    ),
    op!(
        "post",
        "/v1/system/database/backups/{name}/restore",
        "scheduleDatabaseRestore",
        "Database",
        "Stage a backup for restore on restart",
        "202",
        false,
        false,
        Some("RestoreStatus")
    ),
    op!(
        "get",
        "/v1/system/database/restore",
        "databaseRestoreStatus",
        "Database",
        "Get pending and last restore status",
        "200",
        false,
        false,
        Some("RestoreStatus")
    ),
    op!(
        "delete",
        "/v1/system/database/restore",
        "cancelDatabaseRestore",
        "Database",
        "Cancel a pending restore",
        "200",
        false,
        false,
        Some("RestoreStatus")
    ),
    op!(
        "post",
        "/v1/system/maintenance",
        "runMaintenance",
        "Database",
        "Run retention maintenance",
        "200",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/audit",
        "listAudit",
        "Audit",
        "List audit records",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "get",
        "/v1/audit/verify",
        "verifyAuditChain",
        "Audit",
        "Verify the tamper-evident audit hash chain",
        "200",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/secrets",
        "listSecrets",
        "Secrets",
        "List secret references",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/secrets",
        "putSecret",
        "Secrets",
        "Store or update a platform secret",
        "201",
        false,
        true,
        None
    ),
    op!(
        "delete",
        "/v1/secrets/{id}",
        "deleteSecret",
        "Secrets",
        "Delete a secret reference",
        "204",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/system/hosts",
        "listHostProfiles",
        "System",
        "List learned host profiles",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/system/hosts/reset",
        "resetHostProfiles",
        "System",
        "Reset learned host profiles"
    ),
    op!(
        "post",
        "/v1/torrents/probe",
        "probeTorrent",
        "Torrents",
        "Probe a torrent or magnet",
        "200",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/torrents",
        "listManagedTorrents",
        "Torrents",
        "List torrents managed by Ravyn",
        "200",
        true,
        false,
        Some("TorrentPage")
    ),
    op!(
        "get",
        "/v1/torrents/engine",
        "listEngineTorrents",
        "Torrents",
        "List torrents known by rqbit",
        "200",
        false,
        false,
        Some("TorrentEngineList")
    ),
    op!(
        "get",
        "/v1/torrents/engine/stats",
        "torrentEngineStats",
        "Torrents",
        "Get rqbit engine statistics",
        "200",
        false,
        false,
        Some("TorrentGlobalStats")
    ),
    op!(
        "get",
        "/v1/torrents/dht/stats",
        "torrentDhtStats",
        "Torrents",
        "Get DHT statistics"
    ),
    op!(
        "get",
        "/v1/torrents/dht/table",
        "torrentDhtTable",
        "Torrents",
        "Get DHT routing table"
    ),
    op!(
        "get",
        "/v1/torrents/{id}",
        "torrentDetails",
        "Torrents",
        "Get torrent details",
        "200",
        false,
        false,
        Some("TorrentDetails")
    ),
    op!(
        "get",
        "/v1/torrents/{id}/stats",
        "torrentStats",
        "Torrents",
        "Get torrent statistics"
    ),
    op!(
        "get",
        "/v1/torrents/{id}/seeding",
        "torrentSeedingState",
        "Torrents",
        "Get persisted torrent seeding policy state",
        "200",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/torrents/{id}/peers",
        "torrentPeers",
        "Torrents",
        "List torrent peers",
        "200",
        false,
        false,
        Some("TorrentPeerStats")
    ),
    op!(
        "post",
        "/v1/torrents/{id}/peers",
        "addTorrentPeers",
        "Torrents",
        "Add torrent peers",
        "204",
        false,
        true,
        None
    ),
    op!(
        "post",
        "/v1/torrents/{id}/files",
        "updateTorrentFiles",
        "Torrents",
        "Update torrent file selection",
        "204",
        false,
        true,
        None
    ),
    op!(
        "post",
        "/v1/torrents/{id}/remove",
        "removeTorrent",
        "Torrents",
        "Remove a torrent",
        "204",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/rules",
        "listRules",
        "Rules",
        "List rules",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/rules",
        "createRule",
        "Rules",
        "Create a rule",
        "201",
        false,
        true,
        None
    ),
    op!(
        "post",
        "/v1/rules/preview",
        "previewRules",
        "Rules",
        "Preview rule application and scalar conflicts",
        "200",
        false,
        true,
        None
    ),
    op!("get", "/v1/rules/{id}", "getRule", "Rules", "Get a rule"),
    op!(
        "put",
        "/v1/rules/{id}",
        "updateRule",
        "Rules",
        "Replace a rule",
        "200",
        false,
        true,
        None
    ),
    op!(
        "delete",
        "/v1/rules/{id}",
        "deleteRule",
        "Rules",
        "Delete a rule",
        "204",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/tags",
        "listTags",
        "Tags",
        "List tags",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "delete",
        "/v1/tags/{id}",
        "deleteTag",
        "Tags",
        "Delete a tag",
        "204",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/jobs/{id}/tags",
        "listJobTags",
        "Tags",
        "List job tags"
    ),
    op!(
        "put",
        "/v1/jobs/{id}/tags",
        "replaceJobTags",
        "Tags",
        "Replace job tags",
        "200",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/pages",
        "listPages",
        "Pages",
        "List monitored pages",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/pages/resources",
        "listPageResources",
        "Pages",
        "List resources remembered for a page",
        "200",
        false,
        true,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/pages/history/clear",
        "clearPageHistory",
        "Pages",
        "Clear page resource history",
        "200",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/schedules",
        "listSchedules",
        "Schedules",
        "List schedules",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/schedules",
        "createSchedule",
        "Schedules",
        "Create a schedule",
        "201",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/schedules/{id}",
        "getSchedule",
        "Schedules",
        "Get a schedule"
    ),
    op!(
        "put",
        "/v1/schedules/{id}",
        "updateSchedule",
        "Schedules",
        "Replace a schedule",
        "200",
        false,
        true,
        None
    ),
    op!(
        "delete",
        "/v1/schedules/{id}",
        "deleteSchedule",
        "Schedules",
        "Delete a schedule",
        "204",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/schedules/{id}/executions",
        "listScheduleExecutions",
        "Schedules",
        "List schedule executions",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/schedules/{id}/run-now",
        "runScheduleNow",
        "Schedules",
        "Run a schedule immediately",
        "201",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/schedules/{id}/enable",
        "enableSchedule",
        "Schedules",
        "Enable a schedule"
    ),
    op!(
        "post",
        "/v1/schedules/{id}/disable",
        "disableSchedule",
        "Schedules",
        "Disable a schedule"
    ),
    op!(
        "get",
        "/v1/schedule-executions/{id}",
        "getScheduleExecution",
        "Schedules",
        "Get a schedule execution"
    ),
    op!(
        "post",
        "/v1/schedule-executions/{id}/cancel",
        "cancelScheduleExecution",
        "Schedules",
        "Cancel a running schedule execution"
    ),
    op!(
        "get",
        "/v1/browser/tokens",
        "listBrowserTokens",
        "Browser",
        "List browser bridge tokens",
        "200",
        true,
        false,
        Some("GenericPage")
    ),
    op!(
        "post",
        "/v1/browser/tokens",
        "createBrowserToken",
        "Browser",
        "Create a browser bridge token",
        "201",
        false,
        true,
        None
    ),
    op!(
        "delete",
        "/v1/browser/tokens/{id}",
        "revokeBrowserToken",
        "Browser",
        "Revoke a browser bridge token",
        "204",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/browser/sniff",
        "sniffPage",
        "Browser",
        "Sniff static page resources",
        "200",
        false,
        true,
        None
    ),
    op!(
        "post",
        "/v1/browser/import",
        "importBrowserResources",
        "Browser",
        "Import browser-observed resources",
        "207",
        false,
        true,
        None
    ),
    op!(
        "get",
        "/v1/events",
        "streamEvents",
        "Events",
        "Stream replayable server-sent events"
    ),
    op!(
        "get",
        "/v1/components",
        "listComponents",
        "Components",
        "List component and feature status",
        "200",
        false,
        false,
        Some("ComponentOverview")
    ),
    op!(
        "get",
        "/v1/components/manifest",
        "getComponentManifestStatus",
        "Components",
        "Read signed component catalog refresh and cache status",
        "200",
        false,
        false,
        Some("ComponentManifestStatus")
    ),
    op!(
        "post",
        "/v1/components/manifest",
        "refreshComponentManifest",
        "Components",
        "Refresh and verify the remote component catalog",
        "200",
        false,
        false,
        Some("ComponentManifestStatus")
    ),
    op!(
        "post",
        "/v1/components/features",
        "saveFeatureSelections",
        "Components",
        "Save feature selections and setup profile",
        "200",
        false,
        true,
        Some("ComponentOverview")
    ),
    op!(
        "post",
        "/v1/components/{id}/install",
        "installComponent",
        "Components",
        "Install a managed component",
        "202",
        false,
        true,
        None
    ),
    op!(
        "post",
        "/v1/components/{id}/update",
        "updateComponent",
        "Components",
        "Install the verified manifest version of a managed component",
        "202",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/components/{id}/verify",
        "verifyComponent",
        "Components",
        "Run a bounded component health and version check",
        "200",
        false,
        false,
        Some("ComponentHealth")
    ),
    op!(
        "post",
        "/v1/components/{id}/rollback",
        "rollbackComponent",
        "Components",
        "Roll back a component to its previous version",
        "200",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/components/{id}/cleanup",
        "cleanupComponent",
        "Components",
        "Delete superseded managed engine versions and stale download temp files",
        "200",
        false,
        false,
        None
    ),
    op!(
        "delete",
        "/v1/components/{id}",
        "removeComponent",
        "Components",
        "Remove a managed component",
        "204",
        false,
        false,
        None
    ),
    op!(
        "post",
        "/v1/components/{id}/cancel",
        "cancelComponentInstallation",
        "Components",
        "Cancel an active component installation",
        "200",
        false,
        false,
        None
    ),
    op!(
        "get",
        "/v1/setup",
        "getSetupState",
        "Setup",
        "Read first-run and setup completion state",
        "200",
        false,
        false,
        Some("SetupState")
    ),
    op!(
        "post",
        "/v1/setup/library",
        "prepareLibrary",
        "Setup",
        "Validate a library path and create the Ravyn library layout",
        "200",
        false,
        true,
        Some("PrepareLibraryResult")
    ),
    op!(
        "post",
        "/v1/setup/integration-consent",
        "saveIntegrationConsent",
        "Setup",
        "Persist the exact user-approved Windows integration choices",
        "200",
        false,
        true,
        Some("SetupState")
    ),
    op!(
        "post",
        "/v1/setup/installation",
        "reportInstallation",
        "Setup",
        "Report the desktop shell's Windows installation/integration result",
        "200",
        false,
        true,
        Some("SetupState")
    ),
    op!(
        "post",
        "/v1/setup/complete",
        "completeSetup",
        "Setup",
        "Mark setup as complete",
        "200",
        false,
        false,
        Some("SetupState")
    ),
];
